-- DPIA finding R5 (docs/sprint-1-dpia-outline-draft.md): Guardian.consentToken
-- had no expiry, making it a permanent credential. Adds consentTokenExpiresAt
-- as NOT NULL, but this repo's dev database is not empty (Soccernity has no
-- production data -- Decision Log #18 -- but local/manual test rows do
-- exist), so this is split into three steps rather than the single
-- ADD COLUMN ... NOT NULL Prisma generated by default, which fails against
-- any existing row: add nullable, backfill existing rows to a real 72-hour
-- window from now (treating them as freshly issued rather than deleting
-- them), then enforce NOT NULL.

-- AlterTable (nullable first)
ALTER TABLE "Guardian" ADD COLUMN     "consentTokenExpiresAt" TIMESTAMP(3);

-- Backfill any pre-existing rows
UPDATE "Guardian" SET "consentTokenExpiresAt" = NOW() + INTERVAL '72 hours' WHERE "consentTokenExpiresAt" IS NULL;

-- Enforce NOT NULL now that every row has a value
ALTER TABLE "Guardian" ALTER COLUMN "consentTokenExpiresAt" SET NOT NULL;
