import { BadRequestException } from '@nestjs/common';
import {
  formatIsoWeekPeriod,
  getCurrentIsoWeekPeriod,
  getIsoWeekBoundaries,
  getIsoWeekMonday,
  getIsoWeekPeriod,
  getPreviousIsoWeekPeriod,
  isoYearHasWeek53,
  parseIsoWeekPeriod,
} from './iso-week.util';

// Every fixture below was hand-derived independently of this
// implementation (via plain weekday arithmetic anchored on the widely
// documented ISO-8601 fact that 2009-01-01 is a Thursday, and that
// 2024-01-01 is a Monday), NOT generated by running this code and
// asserting on its own output — see the PR report for the full
// derivation chain. This guards against a self-consistent-but-wrong
// implementation passing its own tests.
describe('iso-week.util', () => {
  describe('getIsoWeekPeriod', () => {
    it('the classic ISO-8601 year-boundary example: 2008-12-29 (a Monday) is 2009-W01', () => {
      expect(getIsoWeekPeriod(new Date(Date.UTC(2008, 11, 29)))).toBe('2009-W01');
    });

    it('the sibling year-boundary example: 2010-01-01 (a Friday) is 2009-W53', () => {
      expect(getIsoWeekPeriod(new Date(Date.UTC(2010, 0, 1)))).toBe('2009-W53');
    });

    it('a plain mid-year date: 2026-08-12 (a Wednesday) is 2026-W33', () => {
      expect(getIsoWeekPeriod(new Date(Date.UTC(2026, 7, 12)))).toBe('2026-W33');
    });

    it('every day of the same ISO week maps to the same period', () => {
      // 2026-W33 runs Mon 2026-08-10 through Sun 2026-08-16 (derived
      // independently below in the boundaries test).
      const days = [10, 11, 12, 13, 14, 15, 16].map((d) => new Date(Date.UTC(2026, 7, d)));
      for (const day of days) {
        expect(getIsoWeekPeriod(day)).toBe('2026-W33');
      }
    });

    it('is unaffected by the time-of-day component', () => {
      const midnight = new Date(Date.UTC(2026, 7, 12, 0, 0, 0));
      const lateNight = new Date(Date.UTC(2026, 7, 12, 23, 59, 59));
      expect(getIsoWeekPeriod(midnight)).toBe(getIsoWeekPeriod(lateNight));
    });
  });

  describe('getCurrentIsoWeekPeriod', () => {
    it('delegates to getIsoWeekPeriod for the given/default date', () => {
      const now = new Date(Date.UTC(2026, 7, 12));
      expect(getCurrentIsoWeekPeriod(now)).toBe(getIsoWeekPeriod(now));
    });
  });

  describe('formatIsoWeekPeriod', () => {
    it('zero-pads single-digit weeks', () => {
      expect(formatIsoWeekPeriod(2026, 1)).toBe('2026-W01');
      expect(formatIsoWeekPeriod(2026, 33)).toBe('2026-W33');
      expect(formatIsoWeekPeriod(2009, 53)).toBe('2009-W53');
    });
  });

  describe('isoYearHasWeek53', () => {
    it('2026 has a 53rd week (2026-01-01 is a Thursday)', () => {
      expect(isoYearHasWeek53(2026)).toBe(true);
    });

    it('2015 has a 53rd week (2015-01-01 is a Thursday)', () => {
      expect(isoYearHasWeek53(2015)).toBe(true);
    });

    it('2025 does NOT have a 53rd week (2025-01-01 is a Wednesday, not a leap year)', () => {
      expect(isoYearHasWeek53(2025)).toBe(false);
    });

    it('2016 does NOT have a 53rd week (2016-01-01 is a Friday, even though 2016 is a leap year)', () => {
      expect(isoYearHasWeek53(2016)).toBe(false);
    });
  });

  describe('parseIsoWeekPeriod', () => {
    it('parses a well-formed period', () => {
      expect(parseIsoWeekPeriod('2026-W33')).toEqual({ isoYear: 2026, week: 33 });
    });

    it.each(['2026', '2026-33', '2026-W3', 'not-a-period', '2026-W', ''])(
      'rejects a malformed period string: %s',
      (bad) => {
        expect(() => parseIsoWeekPeriod(bad)).toThrow(BadRequestException);
      },
    );

    it('rejects week 00', () => {
      expect(() => parseIsoWeekPeriod('2026-W00')).toThrow(BadRequestException);
    });

    it('rejects week 54 (never valid for any ISO year)', () => {
      expect(() => parseIsoWeekPeriod('2026-W54')).toThrow(BadRequestException);
    });

    it('accepts week 53 for a year that genuinely has one', () => {
      expect(parseIsoWeekPeriod('2026-W53')).toEqual({ isoYear: 2026, week: 53 });
    });

    it('rejects week 53 for a year that does NOT have one', () => {
      expect(() => parseIsoWeekPeriod('2025-W53')).toThrow(BadRequestException);
    });
  });

  describe('getIsoWeekMonday', () => {
    it('week 1 of 2009 starts on the classic 2008-12-29 Monday', () => {
      const monday = getIsoWeekMonday(2009, 1);
      expect(monday.toISOString()).toBe('2008-12-29T00:00:00.000Z');
    });

    it('week 33 of 2026 starts on 2026-08-10', () => {
      const monday = getIsoWeekMonday(2026, 33);
      expect(monday.toISOString()).toBe('2026-08-10T00:00:00.000Z');
    });
  });

  describe('getIsoWeekBoundaries', () => {
    it('2009-W01 is [2008-12-29T00:00:00Z, 2009-01-05T00:00:00Z)', () => {
      const { start, end } = getIsoWeekBoundaries('2009-W01');
      expect(start.toISOString()).toBe('2008-12-29T00:00:00.000Z');
      expect(end.toISOString()).toBe('2009-01-05T00:00:00.000Z');
    });

    it('2026-W33 is [2026-08-10T00:00:00Z, 2026-08-17T00:00:00Z)', () => {
      const { start, end } = getIsoWeekBoundaries('2026-W33');
      expect(start.toISOString()).toBe('2026-08-10T00:00:00.000Z');
      expect(end.toISOString()).toBe('2026-08-17T00:00:00.000Z');
    });

    it('end is always exactly 7 days after start', () => {
      const { start, end } = getIsoWeekBoundaries('2026-W01');
      expect(end.getTime() - start.getTime()).toBe(7 * 24 * 60 * 60 * 1000);
    });

    it('propagates a BadRequestException for an invalid period', () => {
      expect(() => getIsoWeekBoundaries('garbage')).toThrow(BadRequestException);
    });
  });

  describe('getPreviousIsoWeekPeriod', () => {
    it('the ordinary case: the week before 2026-W33 is 2026-W32', () => {
      expect(getPreviousIsoWeekPeriod('2026-W33')).toBe('2026-W32');
    });

    it('the year-boundary case: the week before 2009-W01 is 2008-W52 (NOT "2009-W00")', () => {
      expect(getPreviousIsoWeekPeriod('2009-W01')).toBe('2008-W52');
    });

    it('round-trips: the previous period\'s own Monday is exactly 7 days before the current period\'s Monday', () => {
      for (const period of ['2026-W01', '2026-W33', '2009-W01', '2026-W53']) {
        const { start: currentMonday } = getIsoWeekBoundaries(period);
        const previous = getPreviousIsoWeekPeriod(period);
        const { start: previousMonday } = getIsoWeekBoundaries(previous);
        expect(currentMonday.getTime() - previousMonday.getTime()).toBe(7 * 24 * 60 * 60 * 1000);
      }
    });
  });
});
